Repository codesquad-member-2020/sidedish-01, pull requests merged in 2020-04, with the labels that each got.

#6 [iOS][#4] 로그인 화면, 메인 화면 구성하고 오토레이아웃 적용하였습니다.
  iOS/.gitignore
  iOS/Sidedish/Sidedish.xcodeproj/project.pbxproj
  iOS/Sidedish/Sidedish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Sidedish/Sidedish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Sidedish/Sidedish/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Sidedish/Sidedish/Assets.xcassets/AppIcon.appiconset/chan (1)-1.png
  iOS/Sidedish/Sidedish/Assets.xcassets/AppIcon.appiconset/chan.png
  iOS/Sidedish/Sidedish/Assets.xcassets/AppIcon.appiconset/chan_1024.png
  iOS/Sidedish/Sidedish/Assets.xcassets/AppIcon.appiconset/chan_152.png
  iOS/Sidedish/Sidedish/Assets.xcassets/AppIcon.appiconset/chan_167.png
  iOS/Sidedish/Sidedish/Assets.xcassets/AppIcon.appiconset/chan_76.png
  iOS/Sidedish/Sidedish/Assets.xcassets/Contents.json
  iOS/Sidedish/Sidedish/Assets.xcassets/baeminChan.imageset/Contents.json
  iOS/Sidedish/Sidedish/Assets.xcassets/baeminChan.imageset/baeminChan.jpeg
  iOS/Sidedish/Sidedish/BMEULJIRO.otf
  iOS/Sidedish/Sidedish/Base.lproj/LaunchScreen.storyboard
  iOS/Sidedish/Sidedish/Base.lproj/Main.storyboard
  iOS/Sidedish/Sidedish/DataSources/MenuTableViewDataSource.swift
  iOS/Sidedish/Sidedish/Delegates/AppDelegate.swift
  iOS/Sidedish/Sidedish/Delegates/SceneDelegate.swift
  iOS/Sidedish/Sidedish/Info.plist
  iOS/Sidedish/Sidedish/Utils/UIColorExtension.swift
  iOS/Sidedish/Sidedish/ViewControllers/LoginViewController.swift
  iOS/Sidedish/Sidedish/ViewControllers/MenuViewController.swift
  iOS/Sidedish/Sidedish/Views/Login's/LoginButton.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/EventBadgeLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/EventBadgeStackView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/FoodProductCell.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/PriceLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/PriceStackView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductImageView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductSubTitleLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductTitleLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/TitleStackView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Header/CategoryLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Header/CategoryTitleLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Header/FoodCategoryHeaderView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/MenuTableView.swift
  iOS/Sidedish/Sidedish/Views/ReusableView.swift
  iOS/Sidedish/SidedishTests/Info.plist
  iOS/Sidedish/SidedishTests/SidedishTests.swift
  iOS/Sidedish/SidedishUITests/Info.plist
  iOS/Sidedish/SidedishUITests/SidedishUITests.swift
Labels: enhancement

#23 [BE] OAuth 2.0 간단한 기능 구현
  BE/side-dish-1/build.gradle
  BE/side-dish-1/build/resources/main/application.properties
  BE/side-dish-1/build/resources/main/schema.sql
  BE/side-dish-1/build/resources/main/static/index.html
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/entity/GitHubTokenInfo.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/entity/Token.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/entity/User.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/repository/TokenRepository.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/repository/UserRepository.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/service/GitHubOauthService.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/service/GitHubOauthServiceImpl.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/value/ResponseUserDTO.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/exception/ErrorMessages.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/exception/ErrorResponse.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/exception/RestExceptionHandler.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/presentation/GitHubOauthController.java
  BE/side-dish-1/src/main/resources/application.properties
  BE/side-dish-1/src/main/resources/schema.sql
  BE/side-dish-1/src/main/resources/static/index.html
Labels: BE, Status : Done, enhancement

#28 [iOS] 성공 모크 스텁 데이터로 메인화면에 데이터를 입혔습니다.
  iOS/Sidedish/Sidedish.xcodeproj/project.pbxproj
  iOS/Sidedish/Sidedish/Base.lproj/Main.storyboard
  iOS/Sidedish/Sidedish/DataSources/MenuTableViewDataSource.swift
  iOS/Sidedish/Sidedish/Delegates/AppDelegate.swift
  iOS/Sidedish/Sidedish/Delegates/SceneDelegate.swift
  iOS/Sidedish/Sidedish/Models/CategoryResponse.swift
  iOS/Sidedish/Sidedish/Models/CategoryURLsResponse.swift
  iOS/Sidedish/Sidedish/Models/ProductDetailResponse.swift
  iOS/Sidedish/Sidedish/Models/Status.swift
  iOS/Sidedish/Sidedish/Network/HTTPRelated.swift
  iOS/Sidedish/Sidedish/Network/Mocks/MockCategorySuccess.swift
  iOS/Sidedish/Sidedish/Network/Mocks/MockCategoryURLsSuccess.swift
  iOS/Sidedish/Sidedish/Network/Mocks/MockProductDetailSuccess.swift
  iOS/Sidedish/Sidedish/Network/NertworkManagable.swift
  iOS/Sidedish/Sidedish/Network/NetworkManager.swift
  iOS/Sidedish/Sidedish/Network/Stubs/DataExtensions.swift
  iOS/Sidedish/Sidedish/Network/Stubs/SuccessCategoryResponseStub.json
  iOS/Sidedish/Sidedish/Network/Stubs/SuccessCategoryURLsResponseStub.json
  iOS/Sidedish/Sidedish/Network/Stubs/SuccessProductDetailResponseStub.json
  iOS/Sidedish/Sidedish/UseCases/CategoryURLsUseCase.swift
  iOS/Sidedish/Sidedish/UseCases/CategoryUseCase.swift
  iOS/Sidedish/Sidedish/ViewControllers/CategoryViewController.swift
  iOS/Sidedish/Sidedish/ViewControllers/MenuViewController.swift
  iOS/Sidedish/Sidedish/ViewModels/CategoryViewModel.swift
  iOS/Sidedish/Sidedish/ViewModels/CategoryViewModels.swift
  iOS/Sidedish/Sidedish/ViewModels/ProductViewModel.swift
  iOS/Sidedish/Sidedish/ViewModels/ViewModelBinding.swift
  iOS/Sidedish/Sidedish/Views/Menu's/CategoryTableView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/EventBadgeLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/EventBadgeStackView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/FoodProductCell.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/PriceStackView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductCell.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductTitleLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/TitleStackView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Header/CategoryHeaderView.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Header/CategoryLabel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Header/CategoryTitleLabel.swift
  iOS/Sidedish/SidedishTests/CodableTests.swift
  iOS/Sidedish/SidedishTests/JsonDataTests.swift
  iOS/Sidedish/SidedishTests/NetworkMockTests.swift
  iOS/Sidedish/SidedishTests/SidedishTests.swift
Labels: JK

#40 [iOS][#38] 이미지 캐싱 기능을 구현하여 풀리퀘스트 보냅니다
  iOS/Sidedish/Sidedish.xcodeproj/project.pbxproj
  iOS/Sidedish/Sidedish/DataSource/CategoryViewModels.swift
  iOS/Sidedish/Sidedish/Info.plist
  iOS/Sidedish/Sidedish/UseCases/ImageUseCase.swift
  iOS/Sidedish/Sidedish/ViewModels/ProductViewModel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductCell.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductImageView.swift
Labels: enhancement, iOS

#41 [BE] OAuth2.0 쿠키를 이용해 user 정보 전달
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/service/GitHubOauthService.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/service/GitHubOauthServiceImpl.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/presentation/GitHubOauthController.java
Labels: BE, enhancement

#45 [BE] 배포 가능 버전 v.1.0.0
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/domain/service/GitHubOauthServiceImpl.java
  BE/side-dish-1/src/main/java/com/codesquad/sidedish1/presentation/TestController.java
  BE/side-dish-1/src/main/resources/application.properties
Labels: BE, enhancement

#46 [iOS] oauth와 실제서버 연동하였습니다.
  iOS/Sidedish/Sidedish.xcodeproj/project.pbxproj
  iOS/Sidedish/Sidedish/Base.lproj/Main.storyboard
  iOS/Sidedish/Sidedish/DataSource/CategoryViewModels.swift
  iOS/Sidedish/Sidedish/Models/CategoryResponse.swift
  iOS/Sidedish/Sidedish/Models/CategoryURLsResponse.swift
  iOS/Sidedish/Sidedish/Models/ProductDetailResponse.swift
  iOS/Sidedish/Sidedish/Models/Status.swift
  iOS/Sidedish/Sidedish/Network/NetworkManager.swift
  iOS/Sidedish/Sidedish/UseCases/CategoryURLsUseCase.swift
  iOS/Sidedish/Sidedish/UseCases/CategoryUseCase.swift
  iOS/Sidedish/Sidedish/UseCases/ImageUseCase.swift
  iOS/Sidedish/Sidedish/UseCases/ProductDetailUseCase.swift
  iOS/Sidedish/Sidedish/ViewControllers/CategoryViewController.swift
  iOS/Sidedish/Sidedish/ViewControllers/LoginViewController.swift
  iOS/Sidedish/Sidedish/ViewModels/ProductViewModel.swift
  iOS/Sidedish/Sidedish/Views/Menu's/Cell/ProductCell.swift
Labels: JK, enhancement, iOS
